### PR TITLE
Added max page number

### PR DESCRIPTION
**Pull request by davidpanic**

### CODE REVIEW

**Comment by Dico200** [comment]
Is this tested?

**Comment by davidpanic** [comment]
@Dico200 it is (now), forgot to math.ceil it

**Comment by jomo** [comment]
Are you sure it's tested? Looks like integer division to me, so math.ceil would have no effect.

**Comment by jomo** [comment]
Would this work?

``` py
"…" % (arg1 + 1, int(math.ceil(len(lols) / float(list_limit))))
```

**Comment by davidpanic** [comment]
oh shite i tested in python3 xD
yep

**Comment by davidpanic** [comment]
lemme just make another commit

**Comment by jomo** [comment]
You don't need the `str` calls though

**Pull request merged**
